[tool.poetry]
name = "peasoup"
version = "0.1.0"
description = ""
authors = ["Peter Kronström <bembu@iki.fi>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.1"
podgen = "^1.0.1"
mutagen = "^1.44.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
